### PR TITLE
Update install-post.sh

### PR DESCRIPTION
**Pull request by Orfeous**
Fix for #8

### CODE REVIEW

**Comment by Orfeous** [comment]
@extremeshok any feedback on this?

**Comment by extremeshok** [comment]
merged, thank you

**Comment by remedycoin** [comment]
Well.  I guess the install did work last night.  So... Maybe I can test this in a virtual machine for you.  The remote installs are painfully slow.  I'm using Dell's IDRAC on an old 1950 machine.  I have to run a 32 bit vm of Windows XP with some ancient Java machine to interoperate with the IDRAC through a VPN. 

I'm very pleased that you have this script available.  It does so much!  

Just tested the reboot-quick command.  Damn!  that was really cool!  Didn't even have to go through the bios post screens.  Took about 30 seconds only if that.

**Comment by remedycoin** [comment]
Patch seems to work for the MOTD issue.
I downloaded the 5.4 iso.  Ran it in a virtual machine.  Reboot and login shows your MOTD there working fine.

When I did this with a 5.3 iso earlier I also noticed that the package "whois" was missing.  I didn't seem to have such a problem this time.  

There were a couple other errors I noticed.  I'll make seperate tickets for them.

**Pull request merged**
